In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
from sklearn import linear_model

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

In [4]:
pop_male = pd.read_csv('1인가구_남자.csv', encoding='cp949', index_col=0)
pop_female = pd.read_csv('1인가구_여자.csv', encoding='cp949', index_col=0)
crime = pd.read_csv('년,월별 총 범죄데이터.csv', encoding='cp949', index_col=0)
crime_rate = pd.read_csv('년도별 범죄율 데이터만.csv', encoding='cp949', index_col=0)
pop = pd.read_csv('자치구별 주민등록인구.csv', encoding='cp949', index_col=0)

In [6]:
df = pd.concat([pop_male, pop_female, crime, crime_rate, pop], axis=1)
df

2020_20대_남자  2020_30대_남자  2020_40대_남자  2020_50대_남자  2021_20대_남자  \
강남구          5736        10181         5750         3512         5733   
강동구          3599         6026         4357         4360         4321   
강북구          3119         3973         3644         4240         3387   
강서구          7431        12363         6444         5323         8264   
관악구         24849        20454         8698         6451        25945   
광진구          8938         7779         4310         4100         9453   
구로구          4476         6645         4490         4330         4928   
금천구          4625         6108         3561         4205         5257   
노원구          5161         4292         3699         3825         5566   
도봉구          1741         2878         2783         3191         1917   
동대문구        10168         5918         4000         4078        11006   
동작구         10444         8266         4031         3075        11117   
마포구          8305         8398         4291         2851         8895   
서대문구         7253         4858         2850         2674         7827   
서초구          3771         6391         3572         2491         3879   
성동구          5789         4873         3196         3206         6139   
성북구          8921         5471         3685         3770         9546   
송파구          5916        10675         6114         4643         6318   
양천구          2333         4267         3200         3451         2581   
영등포구         7260        10209         4950         4566         7879   
용산구          3166         5287         3012         2501         3422   
은평구          4238         6284         4525         4168         4589   
종로구          3438         2707         1757         2011         3488   
중구           2387         2533         1713         1828         2456   
중랑구          3856         5951         4842         6295         4116   

      2021_30대_남자  2021_40대_남자  2021_50대_남자  2022_20대_남자  2022_30대_남자  ...  \
강남구         10501         6018         4008         5765        10686  ...   
강동구          6713         4572         4672         4389         6974  ...   
강북구          4239         3642         4447         3639         4485  ...   
강서구         13593         6877         5584         8684        14599  ...   
관악구         21558         9189         6902        27855        23214  ...   
광진구          8395         4438         4320         9831         9126  ...   
구로구          7304         4575         4550         5289         7999  ...   
금천구          6894         3712         4345         5704         7582  ...   
노원구          4911         3774         4075         5585         5067  ...   
도봉구          3256         2907         3293         1948         3440  ...   
동대문구         6431         4097         4283        11273         6864  ...   
동작구          8968         4269         3272        11802         9519  ...   
마포구          9099         4408         3049         8876         9606  ...   
서대문구         5228         3008         2838         7849         5481  ...   
서초구          6764         3766         2693         3780         6881  ...   
성동구          5298         3237         3311         6386         5394  ...   
성북구          6059         3832         3805         9652         6305  ...   
송파구         11258         6469         4965         6366        11850  ...   
양천구          4767         3318         3558         2665         5089  ...   
영등포구        11268         5132         4783         8167        12060  ...   
용산구          5806         3105         2620         3485         6207  ...   
은평구          6743         4571         4438         4616         7050  ...   
종로구          2882         1768         2095         3656         2908  ...   
중구           2806         1749         1902         2293         3064  ...   
중랑구          6380         4828         6457         4374         6822  ...   

      2020_등록외국인  2020_고령자  2021_세대수  2021_힌국인  2021_등록외국인  2021_고령자  \
강남구   

## 나이브베이즈 분석

In [7]:
X = np.array(pd.DataFrame(df, columns = ['2020_30대_남자', '2021_30대_남자', '2022_30대_남자', '2020_30대_여자', '2021_30대_여자', '2022_30대_여자', '2020_40대_남자', '2021_40대_남자', '2022_40대_남자', '2020_40대_여자', '2021_40대_여자', '2022_40대_여자', '2022_50대_여자']))
y = np.array(pd.DataFrame(df, columns = ['총범죄건수']))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print('X_train :', X_train)
print('X_test :', X_test)
print('y_train : ', y_train)
print('y_test :', y_test)

X_train : [[ 5287  5806  6207  4373  4855  5409  3012  3105  3216  2520  2625  2692
   2071]
 [ 5918  6431  6864  4141  4531  4972  4000  4097  4125  2538  2633  2673
   2653]
 [10181 10501 10686 11286 11137 11018  5750  6018  6172  5804  6178  6384
   3806]
 [ 4873  5298  5394  3844  4072  4272  3196  3237  3228  2458  2547  2603
   2266]
 [ 6645  7304  7999  4593  5050  5559  4490  4575  4677  2779  2830  2970
   2924]
 [ 2878  3256  3440  2085  2347  2548  2783  2907  2888  2066  2139  2217
   2958]
 [ 8398  9099  9606  8562  9049  9495  4291  4408  4599  4278  4443  4592
   3109]
 [ 5951  6380  6822  4440  4838  5371  4842  4828  4857  3062  3251  3332
   4057]
 [ 7779  8395  9126  6904  7407  7989  4310  4438  4413  3258  3373  3579
   3145]
 [ 8266  8968  9519  6111  6735  7057  4031  4269  4316  2897  2987  3178
   2731]
 [ 6026  6713  6974  4755  5482  5891  4357  4572  4557  3172  3412  3571
   3405]
 [ 2533  2806  3064  2140  2462  2629  1713  1749  1742  1280  1344  1413
   

In [14]:
gnb_clf = GaussianNB()
gnb_clf = gnb_clf.fit(X_train, y_train)

c:\Users\DB-26\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
gnb_prediction = gnb_clf.predict(X_test)

In [16]:
fmeasure = round(f1_score(y_test, gnb_prediction, average = 'weighted'), 2)

accuracy = round(accuracy_score(y_test, gnb_prediction, normalize = True), 2)

In [17]:
data_nbclf = pd.DataFrame(columns=['Classifier', 'F-Measure', 'Accuracy'])

data_nbclf.loc[len(data_nbclf)] = ['Naive Bayes', fmeasure, accuracy]

data_nbclf

Classifier  F-Measure  Accuracy
0  Naive Bayes        0.0       0.0

## Decision Tree

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [35]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

# 예측
y_pred = regressor.predict(X_test)

# 회귀 평가 메트릭 계산
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 3556251.9


In [36]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train_index, test_index in kf.split(X, y):
    print('Train set: ', train_index)
    print('Test set: ', test_index)

Train set:  [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19 20 21 22 23 24]
Test set:  [ 0  8 16]
Train set:  [ 0  1  2  3  4  5  6  7  8 10 12 13 14 15 16 17 18 19 20 21 22 24]
Test set:  [ 9 11 23]
Train set:  [ 0  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 20 21 23 24]
Test set:  [ 1 13 22]
Train set:  [ 0  1  3  4  6  7  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24]
Test set:  [ 2  5 12]
Train set:  [ 0  1  2  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23 24]
Test set:  [ 3  4 15]
Train set:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18 19 21 22 23 24]
Test set:  [17 20]
Train set:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 19 20 22 23 24]
Test set:  [18 21]
Train set:  [ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Test set:  [ 7 24]
Train set:  [ 0  1  2  3  4  5  6  7  8  9 11 12 13 15 16 17 18 19 20 21 22 23 24]
Test set:  [10 14]
Train set:  [ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24]

In [40]:
clf = DecisionTreeRegressor()
scores = cross_val_score(clf, X, y, cv=kf, scoring='neg_mean_squared_error')
print('K Fold Cross Validation Score')
print(scores)
print('Average Accuracy')
print(scores.mean())

K Fold Cross Validation Score
[-37078019.66666666  -2447545.33333333   -558520.
  -8251116.33333333  -2580949.66666667  -3402037.
   -391208.5         -1139742.5         -4574889.
  -7731026.        ]
Average Accuracy
-6815505.4


In [41]:
y_pred = clf.predict(X_test)

NotFittedError: This DecisionTreeRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [19]:
print('Confusion Matrix')
print(confusion_matrix(y_test, y_pred))

Confusion Matrix
[[0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]]


In [38]:
print('Accuracy')
print(accuracy_score(y_test, y_pred, normalize=True))

Accuracy
0.0


In [39]:
print('Classification Report')
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

      7395.0       0.00      0.00      0.00       0.0
      7758.0       0.00      0.00      0.00       1.0
      7793.0       0.00      0.00      0.00       0.0
      7946.0       0.00      0.00      0.00       1.0
      8449.0       0.00      0.00      0.00       0.0
      8677.0       0.00      0.00      0.00       1.0
      8852.0       0.00      0.00      0.00       1.0
      9142.0       0.00      0.00      0.00       0.0
      9154.0       0.00      0.00      0.00       1.0
      9173.0       0.00      0.00      0.00       0.0
      9791.0       0.00      0.00      0.00       1.0
      9926.0       0.00      0.00      0.00       0.0
     10105.0       0.00      0.00      0.00       1.0
     10238.0       0.00      0.00      0.00       1.0
     10697.0       0.00      0.00      0.00       1.0
     15204.0       0.00      0.00      0.00       0.0
     20117.0       0.00      0.00      0.00       1.0

    

c:\Users\DB-26\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DB-26\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\DB-26\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [22]:
skf = StratifiedKFold(n_splits=10)
skf.get_n_splits(X, y)
print(skf)

StratifiedKFold(n_splits=10, random_state=None, shuffle=False)


In [25]:
str.count(sub[, start[, end]])

SyntaxError: invalid syntax (364259391.py, line 1)

In [23]:
for train_index, test_index in skf.split(X, y):
    print('Train set: ', train_index)
    print('test set: ', test_index)


ValueError: n_splits=10 cannot be greater than the number of members in each class.

In [24]:
clf = DecisionTreeClassifier()
scores = cross_val_score(clf, X, y, cv=skf)
print('K Fold Cross Validation Score')
print(scores)
print('Average Accuracy')
print(scores.mean())

ValueError: n_splits=10 cannot be greater than the number of members in each class.